/* Generated by Yosys 0.19+36 (git sha1 30a4218f537, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_bidicntr(count, clk, ctrl, reset);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire [7:0] _077_;
  wire [7:0] _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  input clk;
  wire clk;
  output [7:0] count;
  wire [7:0] count;
  input ctrl;
  wire ctrl;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _087_ (
    .A(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _088_ (
    .A(_039_),
    .B(_076_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _089_ (
    .A(_040_),
    .B(_047_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21bai_1 _090_ (
    .A1(_039_),
    .A2(_049_),
    .B1_N(_076_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _091_ (
    .A1(_039_),
    .A2(_049_),
    .B1(_050_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__maj3_1 _092_ (
    .A(_039_),
    .B(_040_),
    .C(_048_),
    .X(_051_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _093_ (
    .A(_041_),
    .SLEEP(_047_),
    .X(_052_)
  );
  sky130_fd_sc_hd__xnor2_1 _094_ (
    .A(_047_),
    .B(_041_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__and2_0 _095_ (
    .A(_051_),
    .B(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _096_ (
    .A(_051_),
    .B(_053_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor3_1 _097_ (
    .A(_076_),
    .B(_054_),
    .C(_055_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _098_ (
    .A(_042_),
    .SLEEP(_047_),
    .X(_056_)
  );
  sky130_fd_sc_hd__xnor2_1 _099_ (
    .A(_047_),
    .B(_042_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor3_1 _100_ (
    .A(_052_),
    .B(_054_),
    .C(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21a_1 _101_ (
    .A1(_052_),
    .A2(_054_),
    .B1(_057_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nor3_1 _102_ (
    .A(_076_),
    .B(_058_),
    .C(_059_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a311o_1 _103_ (
    .A1(_051_),
    .A2(_053_),
    .A3(_057_),
    .B1(_056_),
    .C1(_052_),
    .X(_060_)
  );
  sky130_fd_sc_hd__xnor2_1 _104_ (
    .A(_047_),
    .B(_043_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__and2_0 _105_ (
    .A(_060_),
    .B(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _106_ (
    .A(_060_),
    .B(_061_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor3_1 _107_ (
    .A(_076_),
    .B(_062_),
    .C(_063_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21o_1 _108_ (
    .A1(_048_),
    .A2(_043_),
    .B1(_062_),
    .X(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _109_ (
    .A(_047_),
    .B(_044_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a21oi_1 _110_ (
    .A1(_064_),
    .A2(_065_),
    .B1(_076_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21a_1 _111_ (
    .A1(_064_),
    .A2(_065_),
    .B1(_066_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand3_1 _112_ (
    .A(_060_),
    .B(_061_),
    .C(_065_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o21ai_0 _113_ (
    .A1(_043_),
    .A2(_044_),
    .B1(_048_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _114_ (
    .A(_045_),
    .SLEEP(_047_),
    .X(_069_)
  );
  sky130_fd_sc_hd__xor2_1 _115_ (
    .A(_047_),
    .B(_045_),
    .X(_070_)
  );
  sky130_fd_sc_hd__a21oi_1 _116_ (
    .A1(_067_),
    .A2(_068_),
    .B1(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a31o_1 _117_ (
    .A1(_067_),
    .A2(_068_),
    .A3(_070_),
    .B1(_076_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _118_ (
    .A(_071_),
    .B(_072_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xnor2_1 _119_ (
    .A(_047_),
    .B(_046_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor3_1 _120_ (
    .A(_069_),
    .B(_071_),
    .C(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21a_1 _121_ (
    .A1(_069_),
    .A2(_071_),
    .B1(_073_),
    .X(_075_)
  );
  sky130_fd_sc_hd__nor3_1 _122_ (
    .A(_076_),
    .B(_074_),
    .C(_075_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__dfxtp_1 _123_ (
    .CLK(clk),
    .D(_079_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _124_ (
    .CLK(clk),
    .D(_080_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _125_ (
    .CLK(clk),
    .D(_081_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _126_ (
    .CLK(clk),
    .D(_082_),
    .Q(count[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _127_ (
    .CLK(clk),
    .D(_083_),
    .Q(count[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _128_ (
    .CLK(clk),
    .D(_084_),
    .Q(count[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _129_ (
    .CLK(clk),
    .D(_085_),
    .Q(count[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _130_ (
    .CLK(clk),
    .D(_086_),
    .Q(count[7])
  );
  assign _078_[0] = _077_[0];
  assign _039_ = count[0];
  assign _040_ = count[1];
  assign _047_ = ctrl;
  assign _041_ = count[2];
  assign _042_ = count[3];
  assign _043_ = count[4];
  assign _044_ = count[5];
  assign _045_ = count[6];
  assign _046_ = count[7];
  assign _076_ = reset;
  assign _079_ = _031_;
  assign _080_ = _032_;
  assign _081_ = _033_;
  assign _082_ = _034_;
  assign _083_ = _035_;
  assign _084_ = _036_;
  assign _085_ = _037_;
  assign _086_ = _038_;
endmodule
